from . import crm_lead
from . import sale
from . import vendor_application
from . import account_invoice
from . import stock
from . import web_tour
#from . import res_group
from . import res_users
from . import tbm_api
from . import account_payment
from . import res_partner
from . import tbm_subscription
from . import payment_transaction
from . import project
from . import mail_channel
